/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SeatPlan;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author urmi
 */
public class Arrangement_Student_New extends javax.swing.JFrame {

    /**
     * Creates new form Arrangement_Student
     */
    public Arrangement_Student_New() {
        super("Examination Seating Management System");
        initComponents();
        setSize(750, 400);
                setResizable(false);
		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation(d.width/2-getWidth()/2, d.height/2 - getHeight()/2);
                this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jC = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 130, 60, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 200, 100, 25);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Arrangement Of Student");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 10, 530, 51);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Shift");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 90, 50, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(160, 130, 190, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Day", "Evening" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(580, 90, 130, 30);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(420, 130, 190, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(160, 90, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Semester ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 90, 70, 30);

        jC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Spring", "Summer", "Fall" }));
        jC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCActionPerformed(evt);
            }
        });
        getContentPane().add(jC);
        jC.setBounds(390, 90, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Year");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 90, 40, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 130, 50, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SeatPlan/Nice1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 770, 450);

        jMenu3.setText("Home");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Entry");

        jMenuItem5.setText("Student Info");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Exam Routine");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenu5.setText("Delete");

        jMenuItem10.setText("Exam Routine ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem8.setText("Student Info");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Arrangement");

        jMenuItem1.setText("Create Arrangement");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem7.setText("Delete Arrangement");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem2.setText("Arrangement Report");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("LogOut");
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        try{
            jComboBox6.removeAllItems();
            jComboBox6.addItem("Select");
            Connection con=DBConnection.connect();
            Statement st=con.createStatement();
            String exam_date=(String)jComboBox5.getSelectedItem();
            String msql="Select distinct time from exam_info where split_str(date,' ',1)='"+exam_date+"'";
            ResultSet rs=st.executeQuery(msql);
            while(rs.next()){
                String t=rs.getString(1);
                jComboBox6.addItem(t);
            }rs.close();
            st.close();
            con.close();

        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        // TODO add your handling code here:
        new HomePage();
        this.dispose();
    }//GEN-LAST:event_jMenu6MenuSelected
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Room_No ="502";
        //Date date=jXDatePicker1.getDate();
        String Shift=(String)jComboBox2.getSelectedItem();
        String date=(String)jComboBox5.getSelectedItem();
        String time=(String)jComboBox6.getSelectedItem();
        String semester =(String)jC.getSelectedItem();
        String Year=(String)jComboBox3.getSelectedItem();
       // String Room_No ="502";
        

       if(semester.equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(this, "Semester is mandatory.");
            return;
       }
       if(Year.equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(this, "Year is mandatory.");
            return;
       }
       if(Shift.equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(this, "Shift is mandatory.");
            return;
       }
        if(time .equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(this, "Time  is mandatory.");
            return;
       }
       if(date.equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(this, "Date is mandatory.");
            return;
       }

       String column_nos="";
       int selected_column=2;
    
       try{
           Connection con=DBConnection.connect();
           int courseStd_count=0;
            Statement c_st=con.createStatement();
            String c_msql="SELECT distinct course_code,sec FROM `exam_info` where split_str(date,' ',1)='"+date+"' and time='"+time+"' order by course_code,sec";
            ResultSet c_rs=c_st.executeQuery(c_msql);
            int colmn=0;
            String oldCourse="";
            
            while(c_rs.next()){
                String course_code=c_rs.getString(1);
                String section=c_rs.getString(2);
                
                if(!oldCourse.equals(course_code)){
                    colmn=colmn+1;
                    oldCourse=course_code;
                    Room_No="502";
                }

                
            Statement st=con.createStatement();
            String msql="SELECT ID FROM `studentinfo` where course_code='"+course_code+"' and sec="+section+" and semester='"+semester+"' and year='"+Year+"' order by id";
            ResultSet rs=st.executeQuery(msql);
            while(rs.next()){
                courseStd_count=courseStd_count+1;
                String id=rs.getString(1);
                Boolean isArranged=false;
                
                if((colmn%2) != 0) 
               {
                    column_nos="1,3";
               }
               else 
               {
                    column_nos="2,4";
               }


                Statement check_stmt=con.createStatement();
                String check_sql="SELECT id FROM `arrangement` where ID= '"+id+"' and section = '"+section+"' and shift = '"+Shift+"' and date ='"+date+
                        "' and course_code = '"+course_code+"'";
                ResultSet check_rs1=check_stmt.executeQuery(check_sql);
                String exist_id="";
                while(check_rs1.next()){
                    exist_id=check_rs1.getString(1);
                }
                check_rs1.close();
                check_stmt.close();
                if(!exist_id.equals("")){
                    continue;
                }
                int row_no=0;
                Statement stmt=con.createStatement();
                String msql1="SELECT row_no FROM `room_info` where room_no="+Room_No;
                ResultSet rs1=stmt.executeQuery(msql1);
                while(rs1.next()){
                    row_no=rs1.getInt(1);
                }
                rs1.close();
                stmt.close();
                
                int totalSeat=row_no*selected_column;
                int maxRow=0;
                Statement max_stmt=con.createStatement();
                String max_sql="SELECT count(id) FROM `arrangement` where room_no="+Room_No+" and column_no in ("+column_nos+")";
                ResultSet max_rs=max_stmt.executeQuery(max_sql);
                while(max_rs.next()){
                    maxRow=max_rs.getInt(1);
                }
                max_rs.close();
                max_stmt.close();  
                if(maxRow == totalSeat ){
                    Statement rstmt=con.createStatement();
                    String rmsql1="SELECT room_no FROM `room_info` where room_no >"+Room_No+" order by room_no asc";
                    ResultSet rrs1=rstmt.executeQuery(rmsql1);
                    if(rrs1.next()){
                        Room_No=rrs1.getString(1);
                    }
                    rrs1.close();
                    rstmt.close();
                }
                int roomNo=Integer.parseInt(Room_No);
                
                if((colmn%2) != 0){
                if(isArranged != true){
                    int column=1;
                   for(int r=1;r<=row_no;r++){
                        String s_id="";
                        Statement stmt1=con.createStatement();
                        String msql2="SELECT id FROM `arrangement` where room_no="+Room_No+" and column_no="+column+" and row_no="+r;
                        ResultSet rs2=stmt1.executeQuery(msql2);
                        while(rs2.next()){
                            s_id=rs2.getString(1);
                        }
                        rs2.close();
                        stmt1.close();
                        
                        if(!s_id.equals("")){
                            continue;
                        }
                        else{
                            String sql="INSERT INTO `arrangement`(`room_no`,`ID`,section,shift,date,course_code,column_no,row_no,time,semester,year) VALUES (?,?, ?, ?,?,?,?,?,?,?,?)";
                            PreparedStatement pstmt=con.prepareStatement(sql);
                            pstmt.setInt(1,roomNo);
                             pstmt.setString(2,id);
                             pstmt.setString(3,section);
                             pstmt.setString(4,Shift);
                             pstmt.setString(5, date);
                             pstmt.setString(6,course_code);
                             pstmt.setInt(7,column);
                             pstmt.setInt(8,r);
                             pstmt.setString(9, time);
                             pstmt.setString(10,semester);
                             pstmt.setString(11,Year);
                            int a =pstmt.executeUpdate();
                            if(a > 0){ 
                                isArranged=true;
                                break;
                            }
                            pstmt.close();
                        }
                   } 
                }
                if(isArranged != true){
                    int column=3;
                   for(int r=1;r<=row_no;r++){
                        String s_id="";
                        Statement stmt1=con.createStatement();
                        String msql2="SELECT id FROM `arrangement` where room_no="+Room_No+" and column_no="+column+" and row_no="+r;
                        ResultSet rs2=stmt1.executeQuery(msql2);
                        while(rs2.next()){
                            s_id=rs2.getString(1);
                        }
                        rs2.close();
                        stmt1.close();
                        
                        if(!s_id.equals("")){
                            continue;
                        }
                        else{
                            String sql="INSERT INTO `arrangement`(`room_no`, `ID`,section,shift,date,course_code,column_no,row_no,time,semester,year) VALUES (?,?, ?, ?,?,?,?,?,?,?,?)";
                            PreparedStatement pstmt=con.prepareStatement(sql);
                            pstmt.setInt(1,roomNo);
                             pstmt.setString(2,id);
                             pstmt.setString(3,section);
                             pstmt.setString(4,Shift);
                             pstmt.setString(5, date);
                             pstmt.setString(6,course_code);
                             pstmt.setInt(7,column);
                             pstmt.setInt(8,r);
                             pstmt.setString(9, time);
                             pstmt.setString(10,semester);
                             pstmt.setString(11,Year);
                             
                            int a =pstmt.executeUpdate();
                            if(a > 0){ 
                                isArranged=true;
                                break;
                            }
                            pstmt.close();
                        }
                   } 
                }
                
                }
                else{
                   if(isArranged != true){
                    int column=2;
                   for(int r=1;r<=row_no;r++){
                        String s_id="";
                        Statement stmt1=con.createStatement();
                        String msql2="SELECT id FROM `arrangement` where room_no="+Room_No+" and column_no="+column+" and row_no="+r;
                        ResultSet rs2=stmt1.executeQuery(msql2);
                        while(rs2.next()){
                            s_id=rs2.getString(1);
                        }
                        rs2.close();
                        stmt1.close();
                        
                        if(!s_id.equals("")){
                            continue;
                        }
                        else{
                            String sql="INSERT INTO `arrangement`(`room_no`, `ID`,section,shift,date,course_code,column_no,row_no,time,semester,year) VALUES (?, ?, ?,?,?,?,?,?,?,?,?)";
                            PreparedStatement pstmt=con.prepareStatement(sql);
                            pstmt.setInt(1,roomNo);
                             pstmt.setString(2,id);
                             pstmt.setString(3,section);
                             pstmt.setString(4,Shift);
                             pstmt.setString(5, date);
                             pstmt.setString(6,course_code);
                             pstmt.setInt(7,column);
                             pstmt.setInt(8,r);
                             pstmt.setString(9, time);
                             pstmt.setString(10,semester);
                             pstmt.setString(11,Year);
                            int a =pstmt.executeUpdate();
                            if(a > 0){ 
                                isArranged=true;
                                break;
                            }
                            pstmt.close();
                        }
                   } 
                }
                if(isArranged != true){
                    int column=4;
                   for(int r=1;r<=row_no;r++){
                        String s_id="";
                        Statement stmt1=con.createStatement();
                        String msql2="SELECT id FROM `arrangement` where room_no="+Room_No+" and column_no="+column+" and row_no="+r;
                        ResultSet rs2=stmt1.executeQuery(msql2);
                        while(rs2.next()){
                            s_id=rs2.getString(1);
                        }
                        rs2.close();
                        stmt1.close();
                        
                        if(!s_id.equals("")){
                            continue;
                        }
                        else{
                            String sql="INSERT INTO `arrangement`(`room_no`, `ID`,section,shift,date,course_code,column_no,row_no,time,semester,year) VALUES (?, ?, ?,?,?,?,?,?,?,?,?)";
                            PreparedStatement pstmt=con.prepareStatement(sql);
                            pstmt.setInt(1,roomNo);
                             pstmt.setString(2,id);
                             pstmt.setString(3,section);
                             pstmt.setString(4,Shift);
                             pstmt.setString(5, date);
                             pstmt.setString(6,course_code);
                             pstmt.setInt(7,column);
                             pstmt.setInt(8,r);
                             pstmt.setString(9, time);
                             pstmt.setString(10,semester);
                             pstmt.setString(11,Year);
                             
                            int a =pstmt.executeUpdate();
                            if(a > 0){ 
                                isArranged=true;
                                break;
                            }
                            pstmt.close();
                        }
                   } 
                }
                }
            }
            rs.close();
            st.close();
       }
            if(courseStd_count != 0){
            JOptionPane.showMessageDialog(this, "Saved. Total Student="+courseStd_count);
            return;
           }
           if(courseStd_count == 0){
            JOptionPane.showMessageDialog(this, "No student found for the selected course and section.");
            return;
           }
       }
       catch(Exception e){
            e.printStackTrace();
        }
                                            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         int i;
          for(i=2016;i<=2040;i++){
          jComboBox3.addItem(""+i);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new Student_info();
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new Exam_routine();
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new ExamRoutineUp();
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new StudentInfoUp();
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Arrangement_Student_New();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        // TODO add your handling code here:
        new Entry();
        this.dispose();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
      new ArrangementReport();
      this.dispose();
                       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new ArrangementUp();
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        getExamDate();
       
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCActionPerformed
        // TODO add your handling code here:
         getExamDate();
    }//GEN-LAST:event_jCActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
         getExamDate();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void getExamDate(){
         try{
        String Shift=(String)jComboBox2.getSelectedItem();
        String semester =(String)jC.getSelectedItem();
        String Year=(String)jComboBox3.getSelectedItem();
        jComboBox5.removeAllItems();
        jComboBox5.addItem("Select");
        Connection con=DBConnection.connect();
        Statement st=con.createStatement();
        String msql="Select distinct split_str(date,' ',1) from exam_info where semester='"+semester+"' and year='"+Year+"' and shift='"+Shift+"'";
        ResultSet rs=st.executeQuery(msql);
        while(rs.next()){
           String t=rs.getString(1);
           jComboBox5.addItem(t);
        }
        rs.close();
        st.close();
        con.close();
       }
       catch(Exception e){
           e.printStackTrace();
           
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arrangement_Student_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arrangement_Student_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arrangement_Student_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arrangement_Student_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arrangement_Student_New().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox jC;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
