/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SeatPlan;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author urmi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        super("Examination Seating Management System");
        initComponents();
        setSize(900, 500);
                setResizable(false);
		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation(d.width/2-getWidth()/2, d.height/2 - getHeight()/2);
                this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("User Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 140, 120, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Passward");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 200, 100, 22);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(480, 140, 380, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 300, 120, 31);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel10.setText("User Login");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 10, 220, 51);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Still not a member?Go to Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 80, 480, 29);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(480, 200, 380, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SeatPlan/background-design-14-Cool-Backgrounds.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -60, 910, 570);

        jMenu1.setText("Home");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registration");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("About");

        jMenuItem4.setText("About Developer");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String User_Name =jTextField6.getText();
        String Password =jPasswordField1.getText();
        String LogInType="Admin";
        
        if(User_Name.equals("")){
            JOptionPane.showMessageDialog(this, "User_Name is mandatory.");
            return;
        }
        if(!User_Name.equals("")){

            if(Password.equals("")){
                JOptionPane.showMessageDialog(this, "Password is mandatory.");
                return;
            }
        }
       try{
           
            Connection con=DBConnection.connect();
           // int id=0;
            //int ask=JOptionPane.showConfirmDialog(this, "Do you want to save?","Confirm",0);
            String user=null,pass=null,type=null;
            Statement stmt=con.createStatement();
            String Sql="select * from Registration where user_name='" +User_Name+"'"+";" ;
            ResultSet rs= stmt.executeQuery(Sql);
            while(rs.next()){ 
                 user=rs.getString(1);
                 pass=rs.getString(3);
                 
            
            }
            rs.close();
            
            String checkSql="select type from Registration where user_name='" +User_Name+"'"+";" ;
            ResultSet rst= stmt.executeQuery(checkSql);
            while(rst.next()){
                 type=rst.getString(1);
            }
            rst.close();
            stmt.close();
       if(User_Name.equals(user) && Password.equals(pass))
                        {
                             //JOptionPane.showMessageDialog(null,"  Welcome");  
                          if(LogInType.equals(type)){
                             new Entry();
                             this.dispose();
                          }
                          else{
                             new userEntry();
                             this.dispose();
                          }
                        }
                        else
                        {
                    
                            JOptionPane.showMessageDialog(null,"Invalid User Name and Password");
                            new Login();
                            this.dispose();
                                

                        }
            con.close();
           //new Singleton(User_Name,Password);
    }//GEN-LAST:event_jButton1ActionPerformed
    catch(Exception e){
            e.printStackTrace();
        }
    }
    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
         new HomePage();
         this.dispose();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        new Registration();
        this.dispose();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Developer();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
     
    /**
     * @param args the command line arguments
     */
   
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
